micronaut:
  application:
    name: rest_app_micronaut
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/micronaut_dev`}
    username: backend
    password: backend_dev
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

netty:
  default:
    allocator:
      max-order: 3
